"""
Build the two ICLR26 LaTeX tables from the per-run JSON in ICLR26/eval/.

  1. comparison table — 2-stage training vs the published DAWN-Cast best, for all
     four datasets, with the percentage change of 2-stage over the best.
  2. ablation table   — CIKM and MeteoNet ablations, with the percentage decrement
     each removed component causes.

    python ICLR26/make_tables.py --eval_dir ICLR26/eval --out_dir ICLR26/tables
"""
import argparse, glob, json, os, os.path as osp

# Published DAWN-Cast rows, read off baseline_work_ICLR26/results_table.tex.
# Order: CSI-M, CSI-H2 (2nd-highest threshold), CSI-H (highest), pool4, pool16,
#        HSS, SSIM, MSE
BEST = {
    'sevir':    dict(csi=0.3787, ch2=0.2177, ch=0.1184, p4=0.4211, p16=0.4862,
                     hss=0.4847, ssim=0.6821, mse=340.90, t2=181, t1=219),
    'meteo':    dict(csi=0.4529, ch2=0.4449, ch=0.2758, p4=0.5159, p16=0.6132,
                     hss=0.5890, ssim=0.8419, mse=9.31,   t2=24,  t1=32),
    'shanghai': dict(csi=0.4525, ch2=0.4186, ch=0.3087, p4=0.5113, p16=0.5842,
                     hss=0.5918, ssim=0.7301, mse=25.33,  t2=35,  t1=40),
    'cikm':     dict(csi=0.3411, ch2=0.2424, ch=0.1549, p4=0.3737, p16=0.4282,
                     hss=0.4385, ssim=0.6087, mse=34.13,  t2=35,  t1=40),
}
PRETTY = {'sevir': 'SEVIR', 'meteo': 'MeteoNet', 'shanghai': 'Shanghai', 'cikm': 'CIKM'}
ABL_LABEL = [
    ('none',            r'DAWN-Cast (full model)'),
    ('a_no_wavelet',    r'(a) w/o wavelet transform'),
    ('b_shared_fat',    r'(b) shared FAT blocks (not separate)'),
    ('c_no_gabor',      r'(c) w/o Gabor (MLP $T_{in}\!\to\!T_{out}$)'),
    ('d_no_str',        r'(d) w/o STR module in SRST'),
    ('e_no_spatial',    r'(e) w/o spatial module in SRST'),
    ('f_no_srst',       r'(f) w/o refinement block (SRST)'),
    ('g_no_wgtm',       r'(g) w/o WGTM block'),
]


def load(eval_dir):
    out = {}
    for f in glob.glob(osp.join(eval_dir, '*.json')):
        try:
            d = json.load(open(f))
        except Exception:
            continue
        out[osp.basename(f)[:-5]] = d
    return out


def pct(new, base, higher_better=True):
    """Signed percentage change of `new` relative to `base`."""
    if base in (None, 0) or new is None:
        return None
    d = (new - base) / base * 100.0
    return d if higher_better else -d          # for MSE, lower is an improvement


def fmt(v, dec=4):
    return '--' if v is None else f'{v:.{dec}f}'


def fmt_pct(p):
    if p is None:
        return '--'
    col = 'ForestGreen' if p >= 0 else 'BrickRed'
    return r'\textcolor{%s}{%+.2f\%%}' % (col, p)


def row_metrics(d, ds):
    b = BEST[ds]
    return [
        ('csi',  d.get('test_csi'),                    b['csi'],  True, 4),
        ('ch2',  d.get(f"test_csi_t{b['t2']}"),        b['ch2'],  True, 4),
        ('ch',   d.get(f"test_csi_t{b['t1']}"),        b['ch'],   True, 4),
        ('p4',   d.get('test_csi4'),                   b['p4'],   True, 4),
        ('p16',  d.get('test_csi16'),                  b['p16'],  True, 4),
        ('hss',  d.get('test_hss'),                    b['hss'],  True, 4),
        ('ssim', d.get('test_ssim'),                   b['ssim'], True, 4),
        ('mse',  d.get('test_mse'),                    b['mse'],  False, 2),
    ]


def comparison_table(res, out):
    L = [r'% Generated by ICLR26/make_tables.py',
         r'\begin{table*}[t]', r'\centering',
         r'\caption{Two-stage training (Stage~1: lifting + wavelet temporal path +'
         r' projection; Stage~2: full DAWN-Cast with the Gabor initialised from'
         r' Stage~1) compared against the published DAWN-Cast best model on the'
         r' four pixel-space datasets. All runs are $128\times128$,'
         r' $T_{in}{=}5$, 50 epochs, FACL objective only, evaluated on the test'
         r' split with the best-validation checkpoint. $\Delta$ is the percentage'
         r' change of two-stage over the published best; for MSE a positive'
         r' $\Delta$ denotes a reduction in error. CSI-H and CSI-H2 are the two'
         r' highest intensity thresholds of each dataset.}',
         r'\label{tab:iclr26_twostage_vs_best}',
         r'\resizebox{\textwidth}{!}{%',
         r'\begin{tabular}{l l cccccccc}', r'\toprule',
         r'Dataset & Model & CSI-M$\uparrow$ & CSI-H2$\uparrow$ & CSI-H$\uparrow$ &'
         r' CSI-pool4$\uparrow$ & CSI-pool16$\uparrow$ & HSS$\uparrow$ &'
         r' SSIM$\uparrow$ & MSE$\downarrow$ \\', r'\midrule']
    for ds in ('sevir', 'meteo', 'shanghai', 'cikm'):
        b = BEST[ds]
        run = f'Stage2_pixel_{ds}_seed0'
        d = res.get(run)
        L.append(r'\multirow{3}{*}{%s} & DAWN-Cast (published best) & %s & %s & %s & %s & %s & %s & %s & %s \\'
                 % (PRETTY[ds], fmt(b['csi']), fmt(b['ch2']), fmt(b['ch']),
                    fmt(b['p4']), fmt(b['p16']), fmt(b['hss']), fmt(b['ssim']),
                    fmt(b['mse'], 2)))
        if d is None:
            L.append(r' & Two-stage (ours) & \multicolumn{8}{c}{\textit{evaluation pending}} \\')
            L.append(r' & $\Delta$ vs best & \multicolumn{8}{c}{--} \\')
        else:
            m = row_metrics(d, ds)
            L.append(r' & Two-stage (ours) & ' +
                     ' & '.join(fmt(v, dec) for _, v, _, _, dec in m) + r' \\')
            L.append(r' & $\Delta$ vs best & ' +
                     ' & '.join(fmt_pct(pct(v, base, hb)) for _, v, base, hb, _ in m) + r' \\')
        L.append(r'\midrule' if ds != 'cikm' else r'\bottomrule')
    L += [r'\end{tabular}}', r'\end{table*}']
    open(out, 'w').write('\n'.join(L) + '\n')
    return out


def ablation_table(res, out):
    L = [r'% Generated by ICLR26/make_tables.py',
         r'\begin{table*}[t]', r'\centering',
         r'\caption{Ablation study of DAWN-Cast in pixel space on CIKM and'
         r' MeteoNet. Each variant removes exactly one component; all other'
         r' settings, the initialisation and the 50-epoch FACL schedule are'
         r' identical. $\Delta$ is the percentage change with respect to the'
         r' reference model of that dataset, so a negative value is the'
         r' degradation caused by removing the component.}',
         r'\label{tab:iclr26_ablations}',
         r'\resizebox{\textwidth}{!}{%',
         r'\begin{tabular}{l l cc cc cc}', r'\toprule',
         r'Dataset & Variant & CSI-M$\uparrow$ & $\Delta$CSI &'
         r' HSS$\uparrow$ & $\Delta$HSS & SSIM$\uparrow$ & MSE$\downarrow$ \\',
         r'\midrule']
    any_rows = False
    for ds in ('cikm', 'meteo'):
        rows = []
        for key, label in ABL_LABEL:
            run = (f'Stage2_pixel_{ds}_seed0' if key == 'none'
                   else f'Ablation_pixel_{ds}_{key}_seed0')
            d = res.get(run)
            if d is not None:
                rows.append((label, d, key))
        if not rows:
            continue
        any_rows = True
        ref = BEST[ds]                      # reference = published DAWN-Cast row
        L.append(r'\multicolumn{8}{l}{\textit{%s} — reference: published DAWN-Cast '
                 r'(CSI-M %.4f, HSS %.4f)} \\' % (PRETTY[ds], ref['csi'], ref['hss']))
        for label, d, key in rows:
            c, h = d.get('test_csi'), d.get('test_hss')
            L.append(r' & %s & %s & %s & %s & %s & %s & %s \\' % (
                label, fmt(c), fmt_pct(pct(c, ref['csi'])),
                fmt(h), fmt_pct(pct(h, ref['hss'])),
                fmt(d.get('test_ssim')), fmt(d.get('test_mse'), 2)))
        L.append(r'\midrule')
    if not any_rows:
        L.append(r'\multicolumn{8}{c}{\textit{no ablation evaluations available yet}} \\')
    L[-1] = r'\bottomrule'
    L += [r'\end{tabular}}', r'\end{table*}']
    open(out, 'w').write('\n'.join(L) + '\n')
    return out


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument('--eval_dir', default='ICLR26/eval')
    ap.add_argument('--out_dir', default='ICLR26/tables')
    a = ap.parse_args()
    os.makedirs(a.out_dir, exist_ok=True)
    res = load(a.eval_dir)
    print(f'[tables] loaded {len(res)} evaluated runs')
    f1 = comparison_table(res, osp.join(a.out_dir, 'twostage_vs_best.tex'))
    f2 = ablation_table(res, osp.join(a.out_dir, 'ablations.tex'))
    print(f'[tables] wrote {f1}\n[tables] wrote {f2}')


if __name__ == '__main__':
    main()
