import numpy as np

data = np.load("/home/vatsal/Nowcasting/Datasets/sevir_lr_normalized_resized/valid_2h/vil-2019-SEVIR_VIL_RANDOMEVENTS_2019_0101_0430.h5-3-0.npy")
print(data.min())
print(data.max())
print(data.shape)
print(data.mean())
print(data.std())

data = np.load("/home/vatsal/Dataserver2/Datasets/VIL/vil_mosdac_240_15/valid/01JUN2020_006.npy")
print(data.min())
print(data.max())
print(data.shape)
print(data.mean())
print(data.std())

data = np.load("/home/vatsal/Dataserver2/Datasets/VIL/vil_mosdac_240_15/valid/01JUN2020_006.npy")
print(data.min())
print(data.max())
print(data.shape)
print(data.mean())
print(data.std())

print("/home/vatsal/Dataserver2/Datasets/VIL/vil_mosdac_normalized_240_15/valid/01JUN2020_002.npy")
data = np.load("/home/vatsal/Dataserver2/Datasets/VIL/vil_mosdac_normalized_240_15/valid/01JUN2020_002.npy")
print(data.min())
print(data.max())
print(data.shape)
print(data.mean())
print(data.std())

print("/home/vatsal/Dataserver2/Datasets/VIL/vil_mosdac_240_15/valid/01JUN2020_002.npy")
data = np.load("/home/vatsal/Dataserver2/Datasets/VIL/vil_mosdac_240_15/valid/01JUN2020_002.npy")
print(data.min())
print(data.max())
print(data.shape)
print(data.mean())
print(data.std())

print("/home/vatsal/Dataserver2/Datasets/VIL/VIL_scaled_lr_240_normalized_resized/01AUG2017_060736.npy")
data = np.load("/home/vatsal/Dataserver2/Datasets/VIL/VIL_scaled_lr_240_normalized_resized/01AUG2017_060736.npy")
print(data.min())
print(data.max())
print(data.shape)
print(data.mean())
print(data.std())