"""
Build the final LaTeX table of TEST scores for the DAWN-Cast Gabor-transfer study.

    python -m THE_GABOR.make_latex_table --inputs a.xlsx b.xlsx --out results.tex

Rows are grouped by the regime the model was TRAINED and TESTED on, because the
two groups do not receive the same number of optimiser steps (STORM 62,100 vs
RANDOM 100,000 -- see CHANGELOG.md) and are therefore not directly comparable
across groups.  Best value per column is bolded WITHIN each group only.
"""

import argparse
import os.path as osp
import sys

sys.path.insert(0, osp.dirname(osp.dirname(osp.abspath(__file__))))

import pandas as pd

# metric -> (header, higher_is_better, decimals)
METRICS = [
    ('test_csi',   r'CSI $\uparrow$',        True,  4),
    ('test_csi4',  r'CSI-4 $\uparrow$',      True,  4),
    ('test_csi16', r'CSI-16 $\uparrow$',     True,  4),
    ('test_hss',   r'HSS $\uparrow$',        True,  4),
    ('test_ssim',  r'SSIM $\uparrow$',       True,  4),
    ('test_psnr',  r'PSNR $\uparrow$',       True,  2),
    ('test_mse',   r'MSE $\downarrow$',      False, 1),
    ('test_lpips', r'LPIPS $\downarrow$',    False, 4),
]

# run name -> (group, description, donor, transferred, frozen)
DESC = {
    'DAWNCast_latent_storm_gaborinit_storm_seed0':
        ('storm', r'Gabor init from \textsc{Storm}', r'\textsc{Storm}', r'Gabor', '--'),
    'DAWNCast_latent_storm_gaborinit_random_seed0':
        ('storm', r'Gabor init from \textsc{Random}', r'\textsc{Random}', r'Gabor', '--'),
    'DAWNCast_latent_storm_freezegabor_storm_seed0':
        ('storm', r'Full init, Gabor frozen', r'\textsc{Storm}',
         r'Gabor+MLP+Lift+Proj', r'Gabor'),
    'DAWNCast_latent_storm_frozen_storm_seed0':
        ('storm', r'Full init, all frozen', r'\textsc{Storm}',
         r'Gabor+MLP+Lift+Proj', r'Gabor+MLP+Lift+Proj'),
    'DAWNCast_latent_random_gaborinit_random_seed0':
        ('random', r'Gabor init from \textsc{Random}', r'\textsc{Random}', r'Gabor', '--'),
    'DAWNCast_latent_random_gaborinit_storm_seed0':
        ('random', r'Gabor init from \textsc{Storm}', r'\textsc{Storm}', r'Gabor', '--'),
}

ORDER = {'storm': ['DAWNCast_latent_storm_gaborinit_storm_seed0',
                   'DAWNCast_latent_storm_gaborinit_random_seed0',
                   'DAWNCast_latent_storm_freezegabor_storm_seed0',
                   'DAWNCast_latent_storm_frozen_storm_seed0'],
         'random': ['DAWNCast_latent_random_gaborinit_random_seed0',
                    'DAWNCast_latent_random_gaborinit_storm_seed0']}

GROUP_TITLE = {
    'storm': (r'\textit{Trained and tested on} \textsc{Sevir-Storm} '
              r'(latent; 1{,}242 steps/epoch, 62{,}100 total)'),
    'random': (r'\textit{Trained and tested on} \textsc{Sevir-Random} '
               r'(latent; 2{,}000 steps/epoch, 100{,}000 total)'),
}


def fmt(v, dec):
    return '--' if pd.isna(v) else f'{v:.{dec}f}'


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument('--inputs', nargs='+', required=True)
    ap.add_argument('--out', default='THE_GABOR/results/dawncast_gabor_transfer_table.tex')
    args = ap.parse_args()

    frames = []
    for f in args.inputs:
        d = pd.read_excel(f, sheet_name='results') if f.endswith('.xlsx') else pd.read_csv(f)
        frames.append(d)
    df = pd.concat(frames, ignore_index=True).drop_duplicates(subset=['run'], keep='last')
    df = df.set_index('run')

    L = []
    L.append(r'% Generated by THE_GABOR/make_latex_table.py')
    L.append(r'\begin{table*}[t]')
    L.append(r'\centering')
    L.append(r'\caption{Effect of initialising DAWN-Cast with Gabor parameters '
             r'learned by a controlled Gabor+MLP model on a specific SEVIR '
             r'precipitation regime. All runs are latent-space '
             r'($32\times32\times4$, $T_{\text{in}}{=}5 \rightarrow '
             r'T_{\text{out}}{=}20$), share one identical random initialisation '
             r'(SHA-256 \texttt{05e5ab4a\ldots}), are trained for 50 epochs with '
             r'the FACL objective only, and are evaluated on the test split of '
             r'their own regime using the best-validation checkpoint. '
             r'\emph{Donor} is the regime whose learned Gabor parameters were '
             r'transferred; \emph{Init.} lists the transferred components and '
             r'\emph{Frozen} those held fixed during training. Best value per '
             r'column is bolded within each group; the two groups receive '
             r'different numbers of optimiser steps and are not directly '
             r'comparable to one another.}')
    L.append(r'\label{tab:dawncast_gabor_transfer}')
    L.append(r'\resizebox{\textwidth}{!}{%')
    L.append(r'\begin{tabular}{l l l l ' + 'c' * len(METRICS) + '}')
    L.append(r'\toprule')
    L.append(r'Initialisation & Donor & Init. components & Frozen & '
             + ' & '.join(h for _, h, _, _ in
                          [(k, h, g, d) for k, h, g, d in METRICS]) + r' \\')
    L.append(r'\midrule')

    for gi, group in enumerate(('storm', 'random')):
        runs = [r for r in ORDER[group] if r in df.index]
        if not runs:
            continue
        if gi:
            L.append(r'\addlinespace[2pt]')
            L.append(r'\midrule')
        L.append(r'\multicolumn{' + str(4 + len(METRICS)) + r'}{l}{'
                 + GROUP_TITLE[group] + r'} \\')
        L.append(r'\addlinespace[1pt]')

        best = {}
        for key, _, hi, _ in METRICS:
            vals = [df.loc[r, key] for r in runs if key in df.columns
                    and not pd.isna(df.loc[r, key])]
            if vals:
                best[key] = max(vals) if hi else min(vals)

        for r in runs:
            _, desc, donor, init_c, frozen = DESC[r]
            cells = []
            for key, _, _, dec in METRICS:
                v = df.loc[r, key] if key in df.columns else float('nan')
                s = fmt(v, dec)
                if key in best and not pd.isna(v) and abs(v - best[key]) < 1e-12:
                    s = r'\textbf{' + s + '}'
                cells.append(s)
            L.append(f'{desc} & {donor} & {init_c} & {frozen} & '
                     + ' & '.join(cells) + r' \\')

    L.append(r'\bottomrule')
    L.append(r'\end{tabular}}')
    L.append(r'\end{table*}')

    out = args.out
    os.makedirs(osp.dirname(out), exist_ok=True) if osp.dirname(out) else None
    open(out, 'w').write('\n'.join(L) + '\n')
    print('\n'.join(L))
    print(f'\n[written] {out}')


import os  # noqa: E402
if __name__ == '__main__':
    main()
