"""
Render the Part A CIKM grid (scripts/cikm_valid_combos.csv +
scripts/cikm_rejected_combos.csv) into an organized markdown report.

Read-only over the CSVs -- re-run it any time Part A is re-run.

    python3 scripts/dawncast_cikm_grid_report.py
    python3 scripts/dawncast_cikm_grid_report.py --out scripts/cikm_dawncast_grid_combinations.md
"""

import argparse
import csv
import os.path as osp
from collections import defaultdict
from fractions import Fraction

BUDGET = 15_000_000
HIDDEN_SIZE = 640          # hidden_dim(64) * T_out(10)
N_STR_MODULES = 5          # 2 SRSTResBlock x 2 SRSTBlock + 1 trailing STRModule

# Exact closed form, verified against all 384 instantiated counts (0 mismatches):
#   params = BASE + A*(hsf/nb) + B*hsf + C*(level-1)
BASE = 6_943_129
A = N_STR_MODULES * 4 * HIDDEN_SIZE * HIDDEN_SIZE   # 8,192,000  (w1 + w2)
B = N_STR_MODULES * 2 * HIDDEN_SIZE                 #     6,400  (b1 + b2, hsf part)
C = 74_220                                          # per extra DWT level


def load(path, extra=()):
    out = []
    with open(path) as f:
        for r in csv.DictReader(f):
            row = {k: int(float(r[k])) for k in
                   ('num_blocks', 'hidden_size_factor', 'level', 'total_params')}
            for k in extra:
                row[k] = float(r[k])
            out.append(row)
    return out


def fmt(n):
    return f"{n:,}"


def main():
    here = osp.dirname(osp.abspath(__file__))
    ap = argparse.ArgumentParser()
    ap.add_argument('--valid_csv', default=osp.join(here, 'cikm_valid_combos.csv'))
    ap.add_argument('--rejected_csv', default=osp.join(here, 'cikm_rejected_combos.csv'))
    ap.add_argument('--out', default=osp.join(here, 'cikm_dawncast_grid_combinations.md'))
    ap.add_argument('--budget', type=int, default=BUDGET)
    args = ap.parse_args()

    valid = load(args.valid_csv)
    rejected = load(args.rejected_csv, extra=('overage', 'overage_pct_of_budget'))
    allrows = valid + rejected
    ok = {(r['num_blocks'], r['hidden_size_factor'], r['level']) for r in valid}

    nbs = sorted({r['num_blocks'] for r in allrows})
    hsfs = sorted({r['hidden_size_factor'] for r in allrows})
    levels = sorted({r['level'] for r in allrows})

    L = []
    w = L.append

    # ---------------- header ----------------
    w("# DAWN-Cast — CIKM pixel-space capacity grid")
    w("")
    w(f"All **{len(valid)}** combinations that pass the CIKM hard ceiling of "
      f"**{fmt(args.budget)}** trainable parameters, plus the **{len(rejected)}** rejected.")
    w("")
    w("Generated by `scripts/dawncast_cikm_grid_report.py` from "
      "`cikm_valid_combos.csv` / `cikm_rejected_combos.csv`, which are produced by "
      "`scripts/dawncast_cikm_grid_enumerate.py` (real `sum(p.numel() ...)` counts on "
      "instantiated models, not estimates).")
    w("")
    w("**Fixed:** `hidden_dim=64`, `hf_mode='separate'`, `size_factor=1.0` (resolved "
      "default), `k_spatial=3`, CIKM `T_in=5`, `T_out=10` → `hidden_size = 64*10 = 640`.")
    w("")
    w("**Swept:** `level ∈ {1,2,3,4}`, `hidden_size_factor ∈ {1,2,3,4,6,8}`, "
      "`num_blocks ∈` all 16 divisors of 640.")
    w("")
    w("---")
    w("")

    # ---------------- structure ----------------
    w("## 1. How parameter count is determined (read this first)")
    w("")
    w("The count is **exactly** reproduced by a closed form — checked against all "
      f"{len(allrows)} instantiated models, **0 mismatches**:")
    w("")
    w("```")
    w(f"params = {fmt(BASE)}")
    w(f"       + {fmt(A)} * (hidden_size_factor / num_blocks)")
    w(f"       + {fmt(B)} * hidden_size_factor")
    w(f"       + {fmt(C)} * (level - 1)")
    w("```")
    w("")
    w("The `hsf/nb` term comes from the 5 `STRModule`s in each `WGTMBlock` "
      "(2 `SRSTResBlock` × 2 `SRSTBlock`, + 1 trailing). Each holds "
      "`w1, w2` of shape `(2, nb, bs, bs*hsf)` with `bs = 640/nb`, so "
      "`nb * bs * bs*hsf = 640² * hsf / nb` — the `nb` cancels except as a divisor.")
    w("")
    w(f"The `level` term is one extra HF `FATBlock` per DWT level (because "
      f"`hf_mode='separate'`), dominated by its 1×1×1 `Conv3d` fusion "
      f"`2*(3*64) → 3*64` = 73,920 of the {fmt(C)}. The Gabor/MLP streams inside it "
      "act on `T_in=5 → T_out=10` only, so they contribute almost nothing.")
    w("")
    w("### Three consequences that should drive the selection")
    w("")
    w("**(a) `hidden_size_factor / num_blocks` is the capacity axis.** Not `nb` or "
      "`hsf` individually. It carries ~8.19M params per unit — i.e. essentially the "
      "whole budget. Everything else is rounding.")
    w("")
    w("**(b) `level` is nearly free.** Each extra DWT level adds only "
      f"{fmt(C)} params — **{100.0*C/args.budget:.2f}% of the budget**. Level 1 and "
      "level 4 at the same `(nb, hsf)` differ by 0.22M out of ~7–14M. So `level` is "
      "**not** a capacity knob here; it is a pure architecture knob and is almost "
      "perfectly confounded-free. It can be swept independently of the budget.")
    w("")
    w("**(c) Many `(nb, hsf)` pairs are capacity twins.** Any pair with the same "
      "`hsf/nb` ratio lands within `6,400 * Δhsf` of each other — e.g. `(1,1)`, "
      "`(2,2)`, `(4,4)`, `(8,8)` are all ratio 1.0 and differ by <45k params. They are "
      "*not* the same model — `nb` sets how block-diagonal the Fourier mixing is, "
      "`hsf` sets the width inside each block — but they are indistinguishable on the "
      "parameter budget. Picking several twins spends runs without moving capacity.")
    w("")
    w("---")
    w("")

    # ---------------- capacity tiers ----------------
    w("## 2. Capacity tiers — grouped by `hsf/nb` ratio")
    w("")
    w("This is the table to pick from. Each row is one distinct capacity level. "
      "`params` shown at `level=1`; add "
      f"{fmt(C)} per level above that.")
    w("")
    w("| ratio `hsf/nb` | params @ lvl1 | % of 15M budget | `(num_blocks, hsf)` pairs realizing it | levels surviving |")
    w("|---|---|---|---|---|")

    tiers = defaultdict(list)
    for r in valid:
        tiers[Fraction(r['hidden_size_factor'], r['num_blocks'])].append(r)

    for ratio in sorted(tiers, reverse=True):
        rs = tiers[ratio]
        pairs = sorted({(r['num_blocks'], r['hidden_size_factor']) for r in rs})
        lv = sorted({r['level'] for r in rs})
        p1 = min(r['total_params'] for r in rs)
        pair_s = ", ".join(f"({a},{b})" for a, b in pairs)
        if len(pair_s) > 90:
            pair_s = pair_s[:87] + "…"
        lv_s = "1-4" if lv == [1, 2, 3, 4] else ",".join(map(str, lv))
        w(f"| {ratio} | {fmt(p1)} | {100.0*p1/args.budget:.1f}% | {pair_s} | {lv_s} |")

    w("")
    w(f"**{len(tiers)} distinct capacity tiers** across {len(valid)} combinations — "
      "that is the real number of degrees of freedom on the capacity axis.")
    w("")
    w("---")
    w("")

    # ---------------- pivots ----------------
    w("## 3. Map: params by `num_blocks` × `hidden_size_factor`")
    w("")
    w(f"Values in millions of parameters. ~~struck~~ ✗ = over the "
      f"{args.budget/1e6:.0f}M ceiling, dropped.")
    w("")
    for lvl in levels:
        w(f"### level = {lvl}")
        w("")
        w("| `num_blocks` \\ `hsf` | " + " | ".join(str(h) for h in hsfs) + " |")
        w("|---" * (len(hsfs) + 1) + "|")
        by = {(r['num_blocks'], r['hidden_size_factor']): r
              for r in allrows if r['level'] == lvl}
        for nb in nbs:
            cells = []
            for h in hsfs:
                r = by.get((nb, h))
                if r is None:
                    cells.append("—")
                elif (nb, h, lvl) in ok:
                    cells.append(f"{r['total_params']/1e6:.2f}")
                else:
                    cells.append(f"~~{r['total_params']/1e6:.2f}~~ ✗")
            w(f"| **{nb}** | " + " | ".join(cells) + " |")
        w("")
    w("---")
    w("")

    # ---------------- full list ----------------
    w(f"## 4. All {len(valid)} surviving combinations (sorted by params, ascending)")
    w("")
    w("| # | num_blocks | hidden_size_factor | level | total_params | ratio `hsf/nb` | % budget | run name |")
    w("|---|---|---|---|---|---|---|---|")
    for i, r in enumerate(valid, 1):
        nb, h, lv, p = (r['num_blocks'], r['hidden_size_factor'],
                        r['level'], r['total_params'])
        w(f"| {i} | {nb} | {h} | {lv} | {fmt(p)} | {Fraction(h, nb)} | "
          f"{100.0*p/args.budget:.1f}% | "
          f"`cikm_pixel_dawncast_nb{nb}_hsf{h}_lvl{lv}` |")
    w("")
    w("---")
    w("")

    # ---------------- rejected ----------------
    w(f"## 5. All {len(rejected)} rejected combinations (over {fmt(args.budget)})")
    w("")
    w("| # | num_blocks | hidden_size_factor | level | total_params | over by | % over budget |")
    w("|---|---|---|---|---|---|---|")
    for i, r in enumerate(rejected, 1):
        w(f"| {i} | {r['num_blocks']} | {r['hidden_size_factor']} | {r['level']} | "
          f"{fmt(r['total_params'])} | {fmt(int(r['overage']))} | "
          f"{r['overage_pct_of_budget']:.2f}% |")
    w("")

    with open(args.out, 'w') as f:
        f.write("\n".join(L) + "\n")
    print(f"wrote {args.out}  ({len(L)} lines, {len(valid)} valid + {len(rejected)} rejected)")


if __name__ == '__main__':
    main()
