_wandb:
    value:
        cli_version: 0.19.11
        m: []
        python_version: 3.9.21
        t:
            "1":
                - 1
                - 11
                - 41
                - 49
                - 51
                - 54
                - 55
                - 71
                - 83
            "2":
                - 1
                - 11
                - 41
                - 49
                - 51
                - 54
                - 55
                - 71
                - 83
            "3":
                - 2
                - 13
                - 23
                - 55
                - 61
            "4": 3.9.21
            "5": 0.19.11
            "6": 4.37.2
            "8":
                - 5
            "12": 0.19.11
            "13": linux-x86_64
amp_weight:
    value: 0.01
anet_weight:
    value: 0.1
aw_stop_step:
    value: 5000
backbone:
    value: alphapre
batch_size:
    value: 4
ckpt_milestone:
    value: null
dataset:
    value: meteo
datatype:
    value: vil_vip
early_stop:
    value: 10
ema_rate:
    value: 0.95
epochs:
    value: 50
eval:
    value: false
exp_dir:
    value: meteo
exp_note:
    value: Training
file_rain_seq_add:
    value: 0
frames_in:
    value: 5
frames_out:
    value: 20
generate_outputs:
    value: false
gpu_use:
    value:
        - "0"
grad_acc_step:
    value: 8
img_channel:
    value: 1
img_size:
    value: 128
l2_norm:
    value: 0
layers:
    value: 3
lr:
    value: 0.0001
lr_beta1:
    value: 0.9
lr_beta2:
    value: 0.95
method:
    value: null
mixed_precision:
    value: "no"
num_workers:
    value: 8
out_weight:
    value: 1
patch:
    value: 2
pha_weight:
    value: 0.01
plot_saving_directory:
    value: null
preprocessing:
    value: 0
res_opt:
    value: false
run_name:
    value: Training_meteo_1
scheduler:
    value: cosine
seed:
    value: 0
seq_len:
    value: 25
spec_num:
    value: 20
stride:
    value: 13
tf:
    value: true
tf_changing_rate:
    value: 0
tf_stop_iter:
    value: 2000
training_steps:
    value: 1
valid:
    value: true
valid_limit:
    value: false
visual:
    value: false
vlnum:
    value: 30
wandb_project_name:
    value: Alphapre
wandb_state:
    value: online
warmup_steps:
    value: 1000
