CUDA_VISIBLE_DEVICES=2 python3 run_alphapre_convlstm.py \
    --exp_dir shanghai \
    --exp_note earthfarseer_on_shanghai \
    --batch_size 8 \
    --backbone earthfarseer \
    --dataset shanghai \
    --seq_len 25 \
    --valid \
    --epochs 70 \
    --frames_in 5 \
    --frames_out 20 \
    --num_workers 8 \
    --wandb_state 'offline' \
    --wandb_project_name 'Alphapre_all_other_models' \
    --run_name "earthfarseer_shanghai" 